// <auto-generated />
namespace FacebookComment.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class changing_datatype_of_PostedBy_property_in_Post_Class : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changing_datatype_of_PostedBy_property_in_Post_Class));
        
        string IMigrationMetadata.Id
        {
            get { return "201810191533250_-changing_datatype_of_PostedBy_property_in_Post_Class"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
